name: t_pdf_reader
description: "pdf reader witten by 'than_pdf_engine' package."
version: 0.0.1
homepage: https://github.com/ThanCoder/t_pdf_reader.git
repository: https://github.com/ThanCoder/t_pdf_reader.git

environment:
  sdk: ^3.12.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  dart_core_extensions: ^0.4.0
  than_pdf_engine: ^0.1.0
  pdfium_dart: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
